name: Lint JS and CSS

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: npm
            - name: Install Dependencies
              run: npm ci
            - name: Lint CSS
              run: npm run lint-style
            - name: Lint JS
              run: npm run lint-js
